# Generated by Django 4.0.3 on 2022-03-17 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
